[package]
name = "alex"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
num-derive = "0.4.2"
num-traits = "0.2.19"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
strum = "0.26.2"
strum_macros = "0.26.2"
