[workspace]
members = ["crates/*"]
default-members = ["crates/alex-server"]

[workspace.package]
name = "alex"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
alex = { path = "crates/alex", version = "0.1.0" }
alex-server = { path = "crates/alex-server", version = "0.1.0" }
